2222

diff --git a/.github/workflows/core.yml b/.github/workflows/core.yml
--- a/.github/workflows/core.yml
+++ b/.github/workflows/core.yml
@@ -16,20 +16,31 @@ jobs:
 
       - name: Trigger Elementor-Pro Tests From Core
         run: |
-          response=$(curl -X POST \
-            -H "Authorization: token ${{ secret.REMOTE_GITHUB_KEY }}" \
+          # Print environment for debugging purposes
+          echo "Branch: ${{ env.branch }}"
+          
+          # Set the response and capture the HTTP status code
+          response=$(curl -w "%{http_code}" -o response.txt -s -X POST \
+            -H "Authorization: token ${{ secrets.REMOTE_GITHUB_KEY }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d '{"event_type": "run-from-core", "client_payload": {"branch": "${{ env.branch }}"}}' \
             https://api.github.com/repos/elementor/elementor-pro/dispatches)
-
-          echo "Response: $response"
           
-          if [[ "$response" == *"errors"* ]]; then
-            echo "Error occurred: $response" >&2
+          # Read the response body
+          body=$(cat response.txt)
+
+          # Print the response body and status code
+          echo "Response Body: $body"
+          echo "HTTP Status Code: $response"
+
+          # Check if the HTTP status code indicates an error (non-2xx response)
+          if [[ "$response" -ge 400 ]]; then
+            echo "Error occurred: $body" >&2
             exit 1
-          else
-            echo "Triggered Elementor-Pro tests successfully."
           fi
+          
+          echo "Triggered Elementor-Pro tests successfully."
+
 
 
 #  name: Trigger Remote Workflow
